In [368]:
import numpy as np
import pandas as pd

In [369]:
#Activity 1 (Monday)
#Aggregate data into one Data Frame using Pandas.
file1=pd.read_csv("Data/file1.csv")
file2=pd.read_csv("Data/file2.csv")
file3=pd.read_csv("Data/file3.csv")

#Standardizing header names

def col_lowercase(df):
    df.columns=[i.lower() for i in df.columns]
    
col_lowercase(file1)
col_lowercase(file2)
col_lowercase(file3)


def check_column_consistency(df,df2):
    list1=[]
    list2=[]
    
    #Gather column names from one list
    list1=list(df.columns)
    #Gather column names from second list
    list2=list(df2.columns)
    #Check first list against second, print those not matching
    for j in list2:
        if j not in list1:
            print(j)

print("Checking file1 against file2")
check_column_consistency(file1,file2)
print("Checking file1 against file3")
check_column_consistency(file1,file3)

Checking file1 against file2
Checking file1 against file3
state


In [370]:
file3.rename(columns={"state":"st"},inplace=True)
marketing_df=pd.concat([file1,file2,file3],axis=0,ignore_index=True)
marketing_df


customer          st gender             education  \
0      RB50392  Washington    NaN                Master   
1      QZ44356     Arizona      F              Bachelor   
2      AI49188      Nevada      F              Bachelor   
3      WW63253  California      M              Bachelor   
4      GA49547  Washington      M  High School or Below   
...        ...         ...    ...                   ...   
12069  LA72316  California      M              Bachelor   
12070  PK87824  California      F               College   
12071  TD14365  California      M              Bachelor   
12072  UP19263  California      M               College   
12073  Y167826  California      M               College   

      customer lifetime value   income  monthly premium auto  \
0                         NaN      0.0                1000.0   
1                  697953.59%      0.0                  94.0   
2                 1288743.17%  48767.0                 108.0   
3                  764586.18%      0.0                 106.0   
4                  536307.65%  36357.0                  68.0   
...                       ...      ...                   ...   
12069             23405.98798  71941.0                  73.0   
12070             3096.511217  21604.0                  79.0   
12071             8163.890428      0.0                  85.0   
12072             7524.442436  21941.0                  96.0   
12073             2611.836866      0.0                  77.0   

      number of open complaints     policy type  vehicle class  \
0                        1/0/00   Personal Auto  Four-Door Car   
1                        1/0/00   Personal Auto  Four-Door Car   
2                        1/0/00   Personal Auto   Two-Door Car   
3                        1/0/00  Corporate Auto            SUV   
4                        1/0/00   Personal Auto  Four-Door Car   
...                         ...             ...            ...   
12069                         0   Personal Auto  Four-Door Car   
12070                         0  Corporate Auto  Four-Door Car   
12071                         3  Corporate Auto  Four-Door Car   
12072                         0   Personal Auto  Four-Door Car   
12073                         0  Corporate Auto   Two-Door Car   

       total claim amount  
0                2.704934  
1             1131.464935  
2              566.472247  
3              529.881344  
4               17.269323  
...                   ...  
12069          198.234764  
12070          379.200000  
12071          790.784983  
12072          691.200000  
12073          369.600000  

[12074 rows x 11 columns]

In [371]:
#Deleting and rearranging columns – delete the column customer as it is only a unique identifier for each row of data
marketing_df.drop('customer',axis=1,inplace=True)
marketing_df.rename(columns={'st':'state'},inplace=True)
marketing_df


state gender             education customer lifetime value  \
0      Washington    NaN                Master                     NaN   
1         Arizona      F              Bachelor              697953.59%   
2          Nevada      F              Bachelor             1288743.17%   
3      California      M              Bachelor              764586.18%   
4      Washington      M  High School or Below              536307.65%   
...           ...    ...                   ...                     ...   
12069  California      M              Bachelor             23405.98798   
12070  California      F               College             3096.511217   
12071  California      M              Bachelor             8163.890428   
12072  California      M               College             7524.442436   
12073  California      M               College             2611.836866   

        income  monthly premium auto number of open complaints  \
0          0.0                1000.0                    1/0/00   
1          0.0                  94.0                    1/0/00   
2      48767.0                 108.0                    1/0/00   
3          0.0                 106.0                    1/0/00   
4      36357.0                  68.0                    1/0/00   
...        ...                   ...                       ...   
12069  71941.0                  73.0                         0   
12070  21604.0                  79.0                         0   
12071      0.0                  85.0                         3   
12072  21941.0                  96.0                         0   
12073      0.0                  77.0                         0   

          policy type  vehicle class  total claim amount  
0       Personal Auto  Four-Door Car            2.704934  
1       Personal Auto  Four-Door Car         1131.464935  
2       Personal Auto   Two-Door Car          566.472247  
3      Corporate Auto            SUV          529.881344  
4       Personal Auto  Four-Door Car           17.269323  
...               ...            ...                 ...  
12069   Personal Auto  Four-Door Car          198.234764  
12070  Corporate Auto  Four-Door Car          379.200000  
12071  Corporate Auto  Four-Door Car          790.784983  
12072   Personal Auto  Four-Door Car          691.200000  
12073  Corporate Auto   Two-Door Car          369.600000  

[12074 rows x 10 columns]

In [372]:
#Working with data types – Check the data types of all the columns and fix the incorrect ones 
marketing_df.info()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12074 entries, 0 to 12073
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   state                      9137 non-null   object 
 1   gender                     9015 non-null   object 
 2   education                  9137 non-null   object 
 3   customer lifetime value    9130 non-null   object 
 4   income                     9137 non-null   float64
 5   monthly premium auto       9137 non-null   float64
 6   number of open complaints  9137 non-null   object 
 7   policy type                9137 non-null   object 
 8   vehicle class              9137 non-null   object 
 9   total claim amount         9137 non-null   float64
dtypes: float64(3), object(7)
memory usage: 943.4+ KB


In [373]:
#(for ex. customer lifetime value and number of open complaints ). Hint: remove the percentage from the customer lifetime value and truncate it to an integer value.

#remove % if existing

clv=marketing_df['customer lifetime value']

marketing_df['customer lifetime value']=list(map(lambda x: x.strip("%") if type(x)==str else x,clv))

marketing_df['customer lifetime value'].unique()

array([nan, '697953.59', '1288743.17', ..., 8163.890428, 7524.442436,
       2611.836866], dtype=object)

In [267]:
marketing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12074 entries, 0 to 12073
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   state                      9137 non-null   object 
 1   gender                     9015 non-null   object 
 2   education                  9137 non-null   object 
 3   customer lifetime value    2060 non-null   float64
 4   income                     9137 non-null   float64
 5   monthly premium auto       9137 non-null   float64
 6   number of open complaints  9137 non-null   object 
 7   policy type                9137 non-null   object 
 8   vehicle class              9137 non-null   object 
 9   total claim amount         9137 non-null   float64
dtypes: float64(4), object(6)
memory usage: 943.4+ KB


In [268]:
marketing_df['customer lifetime value']=round((marketing_df['customer lifetime value']/100),2)

In [269]:
marketing_df['customer lifetime value']

0             NaN
1         6979.54
2        12887.43
3         7645.86
4         5363.08
           ...   
12069         NaN
12070         NaN
12071         NaN
12072         NaN
12073         NaN
Name: customer lifetime value, Length: 12074, dtype: float64

In [270]:
#clean the number of open complaints and extract the middle number which is changing between records. 
#pay attention that the number of open complaints is a categorical feature.

#check if value is nan, if so move on

marketing_df['number of open complaints']

x=marketing_df['number of open complaints'][310]
x



'1/1/00'

In [272]:
marketing_df['number of open complaints'] =list(map(lambda x: int(x[2:3]) if type(x)==str else x,marketing_df['number of open complaints']))

x=marketing_df['number of open complaints'][310]
x


1.0

In [260]:
#Filtering data and Correcting typos – Filter the data in state and gender column to standardize the texts in those columns
marketing_df['gender'].unique()

array([nan, 'F', 'M', 'Femal', 'Male', 'female'], dtype=object)

In [277]:
wrong_female_list=['Femal','female']

for i in wrong_female_list:
    mask=marketing_df['gender']==i
    marketing_df.loc[mask,'gender']="F"


mask=marketing_df['gender']=="Male"
marketing_df.loc[mask,'gender']="M"
    
marketing_df['gender'].unique()

array([nan, 'F', 'M'], dtype=object)

In [285]:
states=marketing_df['state']
long_names=['Washington','Arizona','Nevada','California','Oregon','Cali']
short_names=['WA','AZ','NV','CA','OR','CA']
state_zip=dict(zip(long_names,short_names))
marketing_df.replace(state_zip,inplace=True)
states.unique()

array(['WA', 'AZ', 'NV', 'CA', 'OR', nan], dtype=object)

In [286]:
#Removing duplicates
len(marketing_df)

12074

In [290]:
marketing_df.drop_duplicates(inplace=True)

In [291]:
len(marketing_df)

8849

In [294]:
marketing_df.to_csv("data\latest.csv",index=False)